# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="eagle"

# Todo.txt setup
#export TODOTXT_DEFAULT_ACTION=ls
#export TODOTXT_SORT_COMMAND='env LC_COLLATE=C sort -k 2,2 -k 1,1n'
alias t="~/dotfiles/todo-txt/todo.txt-cli/todo.sh -d ~/dotfiles/todo-txt/todo.cfg"
alias todo="t"

alias cpwd="pwd | tr -d '\n' | pbcopy"

bindkey -s '^t' `date +%Y-%m-%d`

# SVN Config
export SVN_EDITOR=vim

# List Servers I Use
alias servers=echo "Blogsmith:\tnate@nate-m01.bsdev.aol.com"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

#fpath=(usr/local/share/zsh/functions $fpath)

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git brew autojump npm osx svn)
#
# https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins
plugins=(git brew autojump npm osx lol)

alias osx-hints='echo "tab - open the current directory in a new tab\npfd - return the path of the frontmost Finder window\npfs - return the current Finder selection\ncdf - cd to the current Finder directory\npushdf - pushd to the current Finder directory\nquick-look - Quick Look a specified file\nman-preview - open a specified man page in Preview\ntrash - move a specified file to the Trash"'

source $ZSH/oh-my-zsh.sh

# http://wiki.office.aol.com/wiki/AOL_Configuration_Management
export GIT_SSH=/usr/bin/ssh

# http://wiki.office.aol.com/wiki/Configuration_Management_GIT_Support
alias gm="$GIT_SSH nate@git.cm.aol.com gitmgr"

# Customize to your needs...
export PATH=~/.cm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/Users/nateeagle5/dotfiles/bin

#[ -s "/Users/nateeagle5/.scm_breeze/scm_breeze.sh" ] && source "/Users/nateeagle5/.scm_breeze/scm_breeze.sh"
